pipeline {
  agent { docker { image 'rajendarreddyj/ant-jdk8-git:latest' } }
  stages {
    stage('Log the Jenkins Docker Ant Git and Java version info') {
      steps {
        sh 'ant -version'
        sh 'java -version'
        sh 'git --version'
      }
    }
    stage('GitHub Jenkins Ant Docker Build') {
      steps {
        /**git clone 'https://github.com/learn-devops-fast/rps-ant.git
        sh 'ant clean compile test package war''**/
      }
    }
  }
}
